<a href="https://colab.research.google.com/github/kanishika-c15/KanishikaUCS420/blob/main/q5assign4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1.

In [2]:

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

add_result = arr + 2
multiply_result = arr * 3
divide_result = arr / 2

print("Original Array:", arr)
print("After Adding 2:", add_result)
print("After Multiplying by 3:", multiply_result)
print("After Dividing by 2:", divide_result)

Original Array: [10 20 30 40 50]
After Adding 2: [12 22 32 42 52]
After Multiplying by 3: [ 30  60  90 120 150]
After Dividing by 2: [ 5. 10. 15. 20. 25.]


Q2

In [6]:

import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)

def most_frequent(arr):
    unique, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_frequent_value = unique[np.argmax(counts)]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_freq_x, indices_x = most_frequent(x)
most_freq_y, indices_y = most_frequent(y)

print(f"Most Frequent in x: {most_freq_x}, Indices: {indices_x}")
print(f"Most Frequent in y: {most_freq_y}, Indices: {indices_y}")


Reversed Array: [5 4 6 3 2 1]
Most Frequent in x: 1, Indices: [0 5 7 8 9]
Most Frequent in y: 1, Indices: [0 1 2]


q3

In [7]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

a = arr[0, 1]
b = arr[2, 0]

print("1st row, 2nd column:", a)
print("3rd row, 1st column:", b)



1st row, 2nd column: 20
3rd row, 1st column: 70


q4


In [8]:
import numpy as np

MyName = np.linspace(10, 100, 25)

print("Array:", MyName)
print("Dimensions:", MyName.ndim)
print("Shape:", MyName.shape)
print("Total Elements:", MyName.size)
print("Data Type:", MyName.dtype)
print("Total Bytes Consumed:", MyName.nbytes)

transposed_array = MyName.reshape(25, 1)
print("Transposed using reshape():\n", transposed_array)

T_transpose = MyName.T
print("Transposed using T attribute:\n", T_transpose)

# Checking if both methods give the same result
print("Can we use T attribute for 1D array?", np.array_equal(transposed_array, T_transpose))



Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes Consumed: 200
Transposed using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Can we use T attribute for 1D array? False


q5

In [9]:
import numpy as np

ucs420_MyName = np.array([[10, 20, 30, 40],
                          [50, 60, 70, 80],
                          [90, 15, 20, 35]])

mean_value = np.mean(ucs420_MyName)
median_value = np.median(ucs420_MyName)
max_value = np.max(ucs420_MyName)
min_value = np.min(ucs420_MyName)
unique_elements = np.unique(ucs420_MyName)

reshaped_ucs420 = ucs420_MyName.reshape(4, 3)

print("Original 2D Array:\n", ucs420_MyName)
print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)
print("Reshaped Array (4x3):\n", reshaped_ucs420)


Original 2D Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
